[package]
name = "localblocksync"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-utils = "0.10.8"
nix = "0.26.2"
clap = { version = "4.1.1", features = ["derive"] }
